# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InternalAuthServiceStub(object):
    """-----------------------------------------------------------------------------
    Internal Services
    -----------------------------------------------------------------------------

    InternalAuthService provides a private API for the ingestion service to
    validate API keys and notify about new data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateApiKey = channel.unary_unary(
                '/ingestion.InternalAuthService/ValidateApiKey',
                request_serializer=auth__pb2.ValidateApiKeyRequest.SerializeToString,
                response_deserializer=auth__pb2.ValidateApiKeyResponse.FromString,
                _registered_method=True)
        self.NotifyNewParquetFile = channel.unary_unary(
                '/ingestion.InternalAuthService/NotifyNewParquetFile',
                request_serializer=auth__pb2.NotifyNewParquetFileRequest.SerializeToString,
                response_deserializer=auth__pb2.NotifyNewParquetFileResponse.FromString,
                _registered_method=True)


class InternalAuthServiceServicer(object):
    """-----------------------------------------------------------------------------
    Internal Services
    -----------------------------------------------------------------------------

    InternalAuthService provides a private API for the ingestion service to
    validate API keys and notify about new data.
    """

    def ValidateApiKey(self, request, context):
        """ValidateApiKey checks if an API key is valid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyNewParquetFile(self, request, context):
        """NotifyNewParquetFile tells the backend to index a newly flushed parquet file.
        Called by ingestion after a cold flush completes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalAuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateApiKey,
                    request_deserializer=auth__pb2.ValidateApiKeyRequest.FromString,
                    response_serializer=auth__pb2.ValidateApiKeyResponse.SerializeToString,
            ),
            'NotifyNewParquetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyNewParquetFile,
                    request_deserializer=auth__pb2.NotifyNewParquetFileRequest.FromString,
                    response_serializer=auth__pb2.NotifyNewParquetFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ingestion.InternalAuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ingestion.InternalAuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternalAuthService(object):
    """-----------------------------------------------------------------------------
    Internal Services
    -----------------------------------------------------------------------------

    InternalAuthService provides a private API for the ingestion service to
    validate API keys and notify about new data.
    """

    @staticmethod
    def ValidateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.InternalAuthService/ValidateApiKey',
            auth__pb2.ValidateApiKeyRequest.SerializeToString,
            auth__pb2.ValidateApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyNewParquetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.InternalAuthService/NotifyNewParquetFile',
            auth__pb2.NotifyNewParquetFileRequest.SerializeToString,
            auth__pb2.NotifyNewParquetFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
