# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\tingestion\"(\n\x15ValidateApiKeyRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"*\n\x16ValidateApiKeyResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32n\n\x13InternalAuthService\x12W\n\x0eValidateApiKey\x12 .ingestion.ValidateApiKeyRequest\x1a!.ingestion.ValidateApiKeyResponse\"\x00\x42\rZ\x0b.;proto_genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013.;proto_gen'
  _globals['_VALIDATEAPIKEYREQUEST']._serialized_start=25
  _globals['_VALIDATEAPIKEYREQUEST']._serialized_end=65
  _globals['_VALIDATEAPIKEYRESPONSE']._serialized_start=67
  _globals['_VALIDATEAPIKEYRESPONSE']._serialized_end=109
  _globals['_INTERNALAUTHSERVICE']._serialized_start=111
  _globals['_INTERNALAUTHSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
