# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ingestion_pb2 as ingestion__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ingestion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InternalIngestionServiceStub(object):
    """InternalIngestionService provides an API for the backend to trigger
    snapshot creation and flushes. The backend reads snapshot files directly
    via DataFusion rather than streaming data over gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareHotSnapshot = channel.unary_unary(
                '/ingestion.InternalIngestionService/PrepareHotSnapshot',
                request_serializer=ingestion__pb2.PrepareHotSnapshotRequest.SerializeToString,
                response_deserializer=ingestion__pb2.PrepareHotSnapshotResponse.FromString,
                _registered_method=True)
        self.FlushWAL = channel.unary_unary(
                '/ingestion.InternalIngestionService/FlushWAL',
                request_serializer=ingestion__pb2.FlushWALRequest.SerializeToString,
                response_deserializer=ingestion__pb2.FlushWALResponse.FromString,
                _registered_method=True)


class InternalIngestionServiceServicer(object):
    """InternalIngestionService provides an API for the backend to trigger
    snapshot creation and flushes. The backend reads snapshot files directly
    via DataFusion rather than streaming data over gRPC.
    """

    def PrepareHotSnapshot(self, request, context):
        """PrepareHotSnapshot flushes pending spans to IPC and creates a stable
        Parquet snapshot file that the backend can read directly without coordination.
        This enables zero-staleness reads without gRPC streaming overhead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlushWAL(self, request, context):
        """FlushWAL triggers an immediate flush of WAL data to cold Parquet storage.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalIngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareHotSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareHotSnapshot,
                    request_deserializer=ingestion__pb2.PrepareHotSnapshotRequest.FromString,
                    response_serializer=ingestion__pb2.PrepareHotSnapshotResponse.SerializeToString,
            ),
            'FlushWAL': grpc.unary_unary_rpc_method_handler(
                    servicer.FlushWAL,
                    request_deserializer=ingestion__pb2.FlushWALRequest.FromString,
                    response_serializer=ingestion__pb2.FlushWALResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ingestion.InternalIngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ingestion.InternalIngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternalIngestionService(object):
    """InternalIngestionService provides an API for the backend to trigger
    snapshot creation and flushes. The backend reads snapshot files directly
    via DataFusion rather than streaming data over gRPC.
    """

    @staticmethod
    def PrepareHotSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.InternalIngestionService/PrepareHotSnapshot',
            ingestion__pb2.PrepareHotSnapshotRequest.SerializeToString,
            ingestion__pb2.PrepareHotSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlushWAL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.InternalIngestionService/FlushWAL',
            ingestion__pb2.FlushWALRequest.SerializeToString,
            ingestion__pb2.FlushWALResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
