// This file is @generated by prost-build.
/// ReadSpansRequest defines the parameters for requesting a batch of spans.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadSpansRequest {
    /// The ULID of the last span successfully processed by the client.
    /// The server will return spans that were received *after* this key.
    /// If empty, the stream will start from the oldest available span.
    #[prost(bytes = "vec", tag = "1")]
    pub start_key_ulid: ::prost::alloc::vec::Vec<u8>,
    /// The maximum number of spans to return in the batch.
    #[prost(uint32, tag = "2")]
    pub batch_size: u32,
}
/// ReadSpansResponse contains a single span from the WAL.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadSpansResponse {
    /// The ULID key of the span, which also serves as its timestamp.
    #[prost(bytes = "vec", tag = "1")]
    pub key_ulid: ::prost::alloc::vec::Vec<u8>,
    /// The raw, serialized protobuf bytes of the OTel span.
    #[prost(bytes = "vec", tag = "2")]
    pub span_bytes: ::prost::alloc::vec::Vec<u8>,
    /// The raw, serialized protobuf bytes of the OTel resource.
    #[prost(bytes = "vec", tag = "3")]
    pub resource_bytes: ::prost::alloc::vec::Vec<u8>,
    /// The number of spans remaining in the WAL after this batch was retrieved.
    /// This count is decremented atomically when the batch is read.
    #[prost(uint64, tag = "4")]
    pub remaining_count: u64,
}
/// GetWALSpansArrowRequest filters spans returned as Arrow IPC.
/// All filters are optional - omit or leave empty to not filter.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetWalSpansArrowRequest {
    /// Filter by trace ID (exact match)
    #[prost(string, optional, tag = "1")]
    pub trace_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Filter by service name (exact match)
    #[prost(string, optional, tag = "2")]
    pub service_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Only return root spans (parent_span_id is empty)
    #[prost(bool, tag = "3")]
    pub root_only: bool,
    /// Only return workflow spans (junjo.span_type = 'workflow')
    #[prost(bool, tag = "4")]
    pub workflow_only: bool,
    /// Maximum number of spans to return (0 = no limit)
    #[prost(int32, tag = "5")]
    pub limit: i32,
}
/// ArrowBatch contains Arrow IPC bytes for efficient columnar data transfer.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ArrowBatch {
    /// Arrow IPC record batch bytes (serialized with ipc.NewWriter)
    #[prost(bytes = "vec", tag = "1")]
    pub ipc_bytes: ::prost::alloc::vec::Vec<u8>,
    /// Number of rows in this batch
    #[prost(int32, tag = "2")]
    pub row_count: i32,
    /// True if this is the last batch in the stream
    #[prost(bool, tag = "3")]
    pub is_last: bool,
}
/// GetHotSpansArrowRequest requests only HOT tier spans (since last warm snapshot).
/// This is more efficient than GetWALSpansArrow as it excludes data already in warm snapshots.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetHotSpansArrowRequest {
    /// Only return spans newer than this ULID.
    /// If empty/null, returns ALL spans in SQLite (fallback when no warm snapshots exist).
    #[prost(bytes = "vec", optional, tag = "1")]
    pub since_warm_ulid: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// Filter by trace ID (exact match)
    #[prost(string, optional, tag = "2")]
    pub trace_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Filter by service name (exact match)
    #[prost(string, optional, tag = "3")]
    pub service_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Only return root spans (parent_span_id is empty)
    #[prost(bool, tag = "4")]
    pub root_only: bool,
    /// Only return workflow spans (junjo.span_type = 'workflow')
    #[prost(bool, tag = "5")]
    pub workflow_only: bool,
    /// Maximum number of spans to return (0 = no limit)
    #[prost(int32, tag = "6")]
    pub limit: i32,
}
/// GetWarmCursorRequest requests the current warm snapshot cursor state.
///
/// Empty - no parameters needed
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetWarmCursorRequest {}
/// GetWarmCursorResponse contains the warm snapshot cursor state.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetWarmCursorResponse {
    /// Last span ULID written to warm snapshot (empty if no snapshots)
    #[prost(bytes = "vec", tag = "1")]
    pub last_warm_ulid: ::prost::alloc::vec::Vec<u8>,
    /// Timestamp of last warm snapshot in nanoseconds
    #[prost(int64, tag = "2")]
    pub last_warm_time_ns: i64,
    /// Number of warm parquet files currently in tmp/
    #[prost(int32, tag = "3")]
    pub warm_file_count: i32,
}
/// GetWALDistinctServiceNamesRequest requests all distinct service names in WAL.
/// DEPRECATED: Use GetHotSpansArrow + DataFusion instead.
///
/// Empty - no parameters needed
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetWalDistinctServiceNamesRequest {}
/// GetWALDistinctServiceNamesResponse contains the list of service names.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetWalDistinctServiceNamesResponse {
    #[prost(string, repeated, tag = "1")]
    pub service_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// FlushWALRequest triggers a manual WAL flush.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlushWalRequest {}
/// FlushWALResponse contains the result of a flush operation.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlushWalResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Error details if success=false
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod internal_ingestion_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// InternalIngestionService provides an API for the main backend to read
    /// spans from the SQLite WAL.
    #[derive(Debug, Clone)]
    pub struct InternalIngestionServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl InternalIngestionServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> InternalIngestionServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InternalIngestionServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            InternalIngestionServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// ReadSpans reads a batch of spans from the WAL, starting after the
        /// specified ULID. This is a server-streaming RPC.
        pub async fn read_spans(
            &mut self,
            request: impl tonic::IntoRequest<super::ReadSpansRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ReadSpansResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ingestion.InternalIngestionService/ReadSpans",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("ingestion.InternalIngestionService", "ReadSpans"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// GetWALSpansArrow returns spans from WAL as Arrow IPC bytes.
        /// Supports filtering by trace_id, service_name, root_only, and workflow_only.
        /// Used for unified DataFusion queries combining WAL and Parquet data.
        pub async fn get_wal_spans_arrow(
            &mut self,
            request: impl tonic::IntoRequest<super::GetWalSpansArrowRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ArrowBatch>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ingestion.InternalIngestionService/GetWALSpansArrow",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ingestion.InternalIngestionService",
                        "GetWALSpansArrow",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// GetHotSpansArrow returns only HOT tier spans (since last warm snapshot).
        /// This is the three-tier architecture query that returns only the newest data.
        pub async fn get_hot_spans_arrow(
            &mut self,
            request: impl tonic::IntoRequest<super::GetHotSpansArrowRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ArrowBatch>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ingestion.InternalIngestionService/GetHotSpansArrow",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ingestion.InternalIngestionService",
                        "GetHotSpansArrow",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// GetWarmCursor returns the current warm snapshot cursor state.
        /// Used by Python to know what's in warm tier vs hot tier.
        pub async fn get_warm_cursor(
            &mut self,
            request: impl tonic::IntoRequest<super::GetWarmCursorRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetWarmCursorResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ingestion.InternalIngestionService/GetWarmCursor",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ingestion.InternalIngestionService",
                        "GetWarmCursor",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GetWALDistinctServiceNames returns all distinct service names currently in the WAL.
        /// Used to merge with Parquet-indexed services for complete listing.
        /// DEPRECATED: Use GetHotSpansArrow + DataFusion instead.
        pub async fn get_wal_distinct_service_names(
            &mut self,
            request: impl tonic::IntoRequest<super::GetWalDistinctServiceNamesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetWalDistinctServiceNamesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ingestion.InternalIngestionService/GetWALDistinctServiceNames",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ingestion.InternalIngestionService",
                        "GetWALDistinctServiceNames",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// FlushWAL triggers an immediate flush of WAL data to Parquet files.
        pub async fn flush_wal(
            &mut self,
            request: impl tonic::IntoRequest<super::FlushWalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FlushWalResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ingestion.InternalIngestionService/FlushWAL",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("ingestion.InternalIngestionService", "FlushWAL"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod internal_ingestion_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with InternalIngestionServiceServer.
    #[async_trait]
    pub trait InternalIngestionService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the ReadSpans method.
        type ReadSpansStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ReadSpansResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// ReadSpans reads a batch of spans from the WAL, starting after the
        /// specified ULID. This is a server-streaming RPC.
        async fn read_spans(
            &self,
            request: tonic::Request<super::ReadSpansRequest>,
        ) -> std::result::Result<tonic::Response<Self::ReadSpansStream>, tonic::Status>;
        /// Server streaming response type for the GetWALSpansArrow method.
        type GetWALSpansArrowStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ArrowBatch, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// GetWALSpansArrow returns spans from WAL as Arrow IPC bytes.
        /// Supports filtering by trace_id, service_name, root_only, and workflow_only.
        /// Used for unified DataFusion queries combining WAL and Parquet data.
        async fn get_wal_spans_arrow(
            &self,
            request: tonic::Request<super::GetWalSpansArrowRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::GetWALSpansArrowStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the GetHotSpansArrow method.
        type GetHotSpansArrowStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ArrowBatch, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// GetHotSpansArrow returns only HOT tier spans (since last warm snapshot).
        /// This is the three-tier architecture query that returns only the newest data.
        async fn get_hot_spans_arrow(
            &self,
            request: tonic::Request<super::GetHotSpansArrowRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::GetHotSpansArrowStream>,
            tonic::Status,
        >;
        /// GetWarmCursor returns the current warm snapshot cursor state.
        /// Used by Python to know what's in warm tier vs hot tier.
        async fn get_warm_cursor(
            &self,
            request: tonic::Request<super::GetWarmCursorRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetWarmCursorResponse>,
            tonic::Status,
        >;
        /// GetWALDistinctServiceNames returns all distinct service names currently in the WAL.
        /// Used to merge with Parquet-indexed services for complete listing.
        /// DEPRECATED: Use GetHotSpansArrow + DataFusion instead.
        async fn get_wal_distinct_service_names(
            &self,
            request: tonic::Request<super::GetWalDistinctServiceNamesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetWalDistinctServiceNamesResponse>,
            tonic::Status,
        >;
        /// FlushWAL triggers an immediate flush of WAL data to Parquet files.
        async fn flush_wal(
            &self,
            request: tonic::Request<super::FlushWalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FlushWalResponse>,
            tonic::Status,
        >;
    }
    /// InternalIngestionService provides an API for the main backend to read
    /// spans from the SQLite WAL.
    #[derive(Debug)]
    pub struct InternalIngestionServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> InternalIngestionServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for InternalIngestionServiceServer<T>
    where
        T: InternalIngestionService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/ingestion.InternalIngestionService/ReadSpans" => {
                    #[allow(non_camel_case_types)]
                    struct ReadSpansSvc<T: InternalIngestionService>(pub Arc<T>);
                    impl<
                        T: InternalIngestionService,
                    > tonic::server::ServerStreamingService<super::ReadSpansRequest>
                    for ReadSpansSvc<T> {
                        type Response = super::ReadSpansResponse;
                        type ResponseStream = T::ReadSpansStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReadSpansRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InternalIngestionService>::read_spans(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReadSpansSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ingestion.InternalIngestionService/GetWALSpansArrow" => {
                    #[allow(non_camel_case_types)]
                    struct GetWALSpansArrowSvc<T: InternalIngestionService>(pub Arc<T>);
                    impl<
                        T: InternalIngestionService,
                    > tonic::server::ServerStreamingService<
                        super::GetWalSpansArrowRequest,
                    > for GetWALSpansArrowSvc<T> {
                        type Response = super::ArrowBatch;
                        type ResponseStream = T::GetWALSpansArrowStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetWalSpansArrowRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InternalIngestionService>::get_wal_spans_arrow(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetWALSpansArrowSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ingestion.InternalIngestionService/GetHotSpansArrow" => {
                    #[allow(non_camel_case_types)]
                    struct GetHotSpansArrowSvc<T: InternalIngestionService>(pub Arc<T>);
                    impl<
                        T: InternalIngestionService,
                    > tonic::server::ServerStreamingService<
                        super::GetHotSpansArrowRequest,
                    > for GetHotSpansArrowSvc<T> {
                        type Response = super::ArrowBatch;
                        type ResponseStream = T::GetHotSpansArrowStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetHotSpansArrowRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InternalIngestionService>::get_hot_spans_arrow(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetHotSpansArrowSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ingestion.InternalIngestionService/GetWarmCursor" => {
                    #[allow(non_camel_case_types)]
                    struct GetWarmCursorSvc<T: InternalIngestionService>(pub Arc<T>);
                    impl<
                        T: InternalIngestionService,
                    > tonic::server::UnaryService<super::GetWarmCursorRequest>
                    for GetWarmCursorSvc<T> {
                        type Response = super::GetWarmCursorResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetWarmCursorRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InternalIngestionService>::get_warm_cursor(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetWarmCursorSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ingestion.InternalIngestionService/GetWALDistinctServiceNames" => {
                    #[allow(non_camel_case_types)]
                    struct GetWALDistinctServiceNamesSvc<T: InternalIngestionService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: InternalIngestionService,
                    > tonic::server::UnaryService<
                        super::GetWalDistinctServiceNamesRequest,
                    > for GetWALDistinctServiceNamesSvc<T> {
                        type Response = super::GetWalDistinctServiceNamesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::GetWalDistinctServiceNamesRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InternalIngestionService>::get_wal_distinct_service_names(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetWALDistinctServiceNamesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ingestion.InternalIngestionService/FlushWAL" => {
                    #[allow(non_camel_case_types)]
                    struct FlushWALSvc<T: InternalIngestionService>(pub Arc<T>);
                    impl<
                        T: InternalIngestionService,
                    > tonic::server::UnaryService<super::FlushWalRequest>
                    for FlushWALSvc<T> {
                        type Response = super::FlushWalResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FlushWalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InternalIngestionService>::flush_wal(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FlushWALSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for InternalIngestionServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "ingestion.InternalIngestionService";
    impl<T> tonic::server::NamedService for InternalIngestionServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateApiKeyRequest {
    /// The API key to be validated.
    #[prost(string, tag = "1")]
    pub api_key: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateApiKeyResponse {
    /// Whether the API key is valid.
    #[prost(bool, tag = "1")]
    pub is_valid: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyNewParquetFileRequest {
    /// Absolute path to the newly created parquet file.
    #[prost(string, tag = "1")]
    pub file_path: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyNewParquetFileResponse {
    /// Whether the file was successfully indexed.
    #[prost(bool, tag = "1")]
    pub indexed: bool,
    /// Number of spans indexed from the file.
    #[prost(int64, tag = "2")]
    pub span_count: i64,
}
/// Generated client implementations.
pub mod internal_auth_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// InternalAuthService provides a private API for the ingestion service to
    /// validate API keys and notify about new data.
    #[derive(Debug, Clone)]
    pub struct InternalAuthServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl InternalAuthServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> InternalAuthServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InternalAuthServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            InternalAuthServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// ValidateApiKey checks if an API key is valid.
        pub async fn validate_api_key(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateApiKeyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateApiKeyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ingestion.InternalAuthService/ValidateApiKey",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("ingestion.InternalAuthService", "ValidateApiKey"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// NotifyNewParquetFile tells the backend to index a newly flushed parquet file.
        /// Called by ingestion after a cold flush completes.
        pub async fn notify_new_parquet_file(
            &mut self,
            request: impl tonic::IntoRequest<super::NotifyNewParquetFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::NotifyNewParquetFileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ingestion.InternalAuthService/NotifyNewParquetFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ingestion.InternalAuthService",
                        "NotifyNewParquetFile",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod internal_auth_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with InternalAuthServiceServer.
    #[async_trait]
    pub trait InternalAuthService: std::marker::Send + std::marker::Sync + 'static {
        /// ValidateApiKey checks if an API key is valid.
        async fn validate_api_key(
            &self,
            request: tonic::Request<super::ValidateApiKeyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateApiKeyResponse>,
            tonic::Status,
        >;
        /// NotifyNewParquetFile tells the backend to index a newly flushed parquet file.
        /// Called by ingestion after a cold flush completes.
        async fn notify_new_parquet_file(
            &self,
            request: tonic::Request<super::NotifyNewParquetFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::NotifyNewParquetFileResponse>,
            tonic::Status,
        >;
    }
    /// InternalAuthService provides a private API for the ingestion service to
    /// validate API keys and notify about new data.
    #[derive(Debug)]
    pub struct InternalAuthServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> InternalAuthServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for InternalAuthServiceServer<T>
    where
        T: InternalAuthService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/ingestion.InternalAuthService/ValidateApiKey" => {
                    #[allow(non_camel_case_types)]
                    struct ValidateApiKeySvc<T: InternalAuthService>(pub Arc<T>);
                    impl<
                        T: InternalAuthService,
                    > tonic::server::UnaryService<super::ValidateApiKeyRequest>
                    for ValidateApiKeySvc<T> {
                        type Response = super::ValidateApiKeyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ValidateApiKeyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InternalAuthService>::validate_api_key(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ValidateApiKeySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ingestion.InternalAuthService/NotifyNewParquetFile" => {
                    #[allow(non_camel_case_types)]
                    struct NotifyNewParquetFileSvc<T: InternalAuthService>(pub Arc<T>);
                    impl<
                        T: InternalAuthService,
                    > tonic::server::UnaryService<super::NotifyNewParquetFileRequest>
                    for NotifyNewParquetFileSvc<T> {
                        type Response = super::NotifyNewParquetFileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::NotifyNewParquetFileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InternalAuthService>::notify_new_parquet_file(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = NotifyNewParquetFileSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for InternalAuthServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "ingestion.InternalAuthService";
    impl<T> tonic::server::NamedService for InternalAuthServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
