// Generated proto modules
// These files are generated by tonic-build in build.rs

// OpenTelemetry common types
pub mod opentelemetry {
    pub mod proto {
        pub mod common {
            pub mod v1 {
                include!("opentelemetry.proto.common.v1.rs");
            }
        }
        pub mod resource {
            pub mod v1 {
                include!("opentelemetry.proto.resource.v1.rs");
            }
        }
        pub mod trace {
            pub mod v1 {
                include!("opentelemetry.proto.trace.v1.rs");
            }
        }
        pub mod collector {
            pub mod trace {
                pub mod v1 {
                    include!("opentelemetry.proto.collector.trace.v1.rs");
                }
            }
        }
    }
}

// Internal service protos
pub mod ingestion {
    include!("ingestion.rs");
}

pub mod span_data_container {
    include!("span_data_container.rs");
}

// Re-exports for convenience
pub use opentelemetry::proto::collector::trace::v1::trace_service_server::TraceServiceServer;

pub use ingestion::internal_ingestion_service_server::InternalIngestionServiceServer;
