// This file is @generated by prost-build.
/// SpanDataContainer is a wrapper for storing a span and its resource together.
/// This is used internally by the ingestion service to persist spans and their
/// associated resources together in SQLite.
///
/// Note: This is an internal-only proto, not part of the gRPC service API.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpanDataContainer {
    #[prost(bytes = "vec", tag = "1")]
    pub span_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub resource_bytes: ::prost::alloc::vec::Vec<u8>,
}
