// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: auth.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateApiKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The API key to be validated.
	ApiKey        string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateApiKeyRequest) Reset() {
	*x = ValidateApiKeyRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateApiKeyRequest) ProtoMessage() {}

func (x *ValidateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateApiKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ValidateApiKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the API key is valid.
	IsValid       bool `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateApiKeyResponse) Reset() {
	*x = ValidateApiKeyResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateApiKeyResponse) ProtoMessage() {}

func (x *ValidateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateApiKeyResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type NotifyNewParquetFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path to the newly created parquet file.
	FilePath      string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNewParquetFileRequest) Reset() {
	*x = NotifyNewParquetFileRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewParquetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewParquetFileRequest) ProtoMessage() {}

func (x *NotifyNewParquetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewParquetFileRequest.ProtoReflect.Descriptor instead.
func (*NotifyNewParquetFileRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyNewParquetFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type NotifyNewParquetFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the file was successfully indexed.
	Indexed bool `protobuf:"varint,1,opt,name=indexed,proto3" json:"indexed,omitempty"`
	// Number of spans indexed from the file.
	SpanCount     int64 `protobuf:"varint,2,opt,name=span_count,json=spanCount,proto3" json:"span_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNewParquetFileResponse) Reset() {
	*x = NotifyNewParquetFileResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewParquetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewParquetFileResponse) ProtoMessage() {}

func (x *NotifyNewParquetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewParquetFileResponse.ProtoReflect.Descriptor instead.
func (*NotifyNewParquetFileResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyNewParquetFileResponse) GetIndexed() bool {
	if x != nil {
		return x.Indexed
	}
	return false
}

func (x *NotifyNewParquetFileResponse) GetSpanCount() int64 {
	if x != nil {
		return x.SpanCount
	}
	return 0
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\tingestion\"0\n" +
	"\x15ValidateApiKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"3\n" +
	"\x16ValidateApiKeyResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\":\n" +
	"\x1bNotifyNewParquetFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"W\n" +
	"\x1cNotifyNewParquetFileResponse\x12\x18\n" +
	"\aindexed\x18\x01 \x01(\bR\aindexed\x12\x1d\n" +
	"\n" +
	"span_count\x18\x02 \x01(\x03R\tspanCount2\xd9\x01\n" +
	"\x13InternalAuthService\x12W\n" +
	"\x0eValidateApiKey\x12 .ingestion.ValidateApiKeyRequest\x1a!.ingestion.ValidateApiKeyResponse\"\x00\x12i\n" +
	"\x14NotifyNewParquetFile\x12&.ingestion.NotifyNewParquetFileRequest\x1a'.ingestion.NotifyNewParquetFileResponse\"\x00B\rZ\v.;proto_genb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_proto_goTypes = []any{
	(*ValidateApiKeyRequest)(nil),        // 0: ingestion.ValidateApiKeyRequest
	(*ValidateApiKeyResponse)(nil),       // 1: ingestion.ValidateApiKeyResponse
	(*NotifyNewParquetFileRequest)(nil),  // 2: ingestion.NotifyNewParquetFileRequest
	(*NotifyNewParquetFileResponse)(nil), // 3: ingestion.NotifyNewParquetFileResponse
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: ingestion.InternalAuthService.ValidateApiKey:input_type -> ingestion.ValidateApiKeyRequest
	2, // 1: ingestion.InternalAuthService.NotifyNewParquetFile:input_type -> ingestion.NotifyNewParquetFileRequest
	1, // 2: ingestion.InternalAuthService.ValidateApiKey:output_type -> ingestion.ValidateApiKeyResponse
	3, // 3: ingestion.InternalAuthService.NotifyNewParquetFile:output_type -> ingestion.NotifyNewParquetFileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
