// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: ingestion.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadSpansRequest defines the parameters for requesting a batch of spans.
type ReadSpansRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ULID of the last span successfully processed by the client.
	// The server will return spans that were received *after* this key.
	// If empty, the stream will start from the oldest available span.
	StartKeyUlid []byte `protobuf:"bytes,1,opt,name=start_key_ulid,json=startKeyUlid,proto3" json:"start_key_ulid,omitempty"`
	// The maximum number of spans to return in the batch.
	BatchSize     uint32 `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSpansRequest) Reset() {
	*x = ReadSpansRequest{}
	mi := &file_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSpansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSpansRequest) ProtoMessage() {}

func (x *ReadSpansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSpansRequest.ProtoReflect.Descriptor instead.
func (*ReadSpansRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *ReadSpansRequest) GetStartKeyUlid() []byte {
	if x != nil {
		return x.StartKeyUlid
	}
	return nil
}

func (x *ReadSpansRequest) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

// ReadSpansResponse contains a single span from the WAL.
type ReadSpansResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ULID key of the span, which also serves as its timestamp.
	KeyUlid []byte `protobuf:"bytes,1,opt,name=key_ulid,json=keyUlid,proto3" json:"key_ulid,omitempty"`
	// The raw, serialized protobuf bytes of the OTel span.
	SpanBytes []byte `protobuf:"bytes,2,opt,name=span_bytes,json=spanBytes,proto3" json:"span_bytes,omitempty"`
	// The raw, serialized protobuf bytes of the OTel resource.
	ResourceBytes []byte `protobuf:"bytes,3,opt,name=resource_bytes,json=resourceBytes,proto3" json:"resource_bytes,omitempty"`
	// The number of spans remaining in the WAL after this batch was retrieved.
	// This count is decremented atomically when the batch is read.
	RemainingCount uint64 `protobuf:"varint,4,opt,name=remaining_count,json=remainingCount,proto3" json:"remaining_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadSpansResponse) Reset() {
	*x = ReadSpansResponse{}
	mi := &file_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSpansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSpansResponse) ProtoMessage() {}

func (x *ReadSpansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSpansResponse.ProtoReflect.Descriptor instead.
func (*ReadSpansResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *ReadSpansResponse) GetKeyUlid() []byte {
	if x != nil {
		return x.KeyUlid
	}
	return nil
}

func (x *ReadSpansResponse) GetSpanBytes() []byte {
	if x != nil {
		return x.SpanBytes
	}
	return nil
}

func (x *ReadSpansResponse) GetResourceBytes() []byte {
	if x != nil {
		return x.ResourceBytes
	}
	return nil
}

func (x *ReadSpansResponse) GetRemainingCount() uint64 {
	if x != nil {
		return x.RemainingCount
	}
	return 0
}

// GetWALSpansArrowRequest filters spans returned as Arrow IPC.
// All filters are optional - omit or leave empty to not filter.
type GetWALSpansArrowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by trace ID (exact match)
	TraceId *string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3,oneof" json:"trace_id,omitempty"`
	// Filter by service name (exact match)
	ServiceName *string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3,oneof" json:"service_name,omitempty"`
	// Only return root spans (parent_span_id is empty)
	RootOnly bool `protobuf:"varint,3,opt,name=root_only,json=rootOnly,proto3" json:"root_only,omitempty"`
	// Only return workflow spans (junjo.span_type = 'workflow')
	WorkflowOnly bool `protobuf:"varint,4,opt,name=workflow_only,json=workflowOnly,proto3" json:"workflow_only,omitempty"`
	// Maximum number of spans to return (0 = no limit)
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALSpansArrowRequest) Reset() {
	*x = GetWALSpansArrowRequest{}
	mi := &file_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALSpansArrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALSpansArrowRequest) ProtoMessage() {}

func (x *GetWALSpansArrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALSpansArrowRequest.ProtoReflect.Descriptor instead.
func (*GetWALSpansArrowRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *GetWALSpansArrowRequest) GetTraceId() string {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return ""
}

func (x *GetWALSpansArrowRequest) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

func (x *GetWALSpansArrowRequest) GetRootOnly() bool {
	if x != nil {
		return x.RootOnly
	}
	return false
}

func (x *GetWALSpansArrowRequest) GetWorkflowOnly() bool {
	if x != nil {
		return x.WorkflowOnly
	}
	return false
}

func (x *GetWALSpansArrowRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ArrowBatch contains Arrow IPC bytes for efficient columnar data transfer.
type ArrowBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arrow IPC record batch bytes (serialized with ipc.NewWriter)
	IpcBytes []byte `protobuf:"bytes,1,opt,name=ipc_bytes,json=ipcBytes,proto3" json:"ipc_bytes,omitempty"`
	// Number of rows in this batch
	RowCount int32 `protobuf:"varint,2,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	// True if this is the last batch in the stream
	IsLast        bool `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowBatch) Reset() {
	*x = ArrowBatch{}
	mi := &file_ingestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowBatch) ProtoMessage() {}

func (x *ArrowBatch) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowBatch.ProtoReflect.Descriptor instead.
func (*ArrowBatch) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{3}
}

func (x *ArrowBatch) GetIpcBytes() []byte {
	if x != nil {
		return x.IpcBytes
	}
	return nil
}

func (x *ArrowBatch) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *ArrowBatch) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// GetHotSpansArrowRequest requests only HOT tier spans (since last warm snapshot).
// This is more efficient than GetWALSpansArrow as it excludes data already in warm snapshots.
type GetHotSpansArrowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only return spans newer than this ULID.
	// If empty/null, returns ALL spans in SQLite (fallback when no warm snapshots exist).
	SinceWarmUlid []byte `protobuf:"bytes,1,opt,name=since_warm_ulid,json=sinceWarmUlid,proto3,oneof" json:"since_warm_ulid,omitempty"`
	// Filter by trace ID (exact match)
	TraceId *string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3,oneof" json:"trace_id,omitempty"`
	// Filter by service name (exact match)
	ServiceName *string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3,oneof" json:"service_name,omitempty"`
	// Only return root spans (parent_span_id is empty)
	RootOnly bool `protobuf:"varint,4,opt,name=root_only,json=rootOnly,proto3" json:"root_only,omitempty"`
	// Only return workflow spans (junjo.span_type = 'workflow')
	WorkflowOnly bool `protobuf:"varint,5,opt,name=workflow_only,json=workflowOnly,proto3" json:"workflow_only,omitempty"`
	// Maximum number of spans to return (0 = no limit)
	Limit         int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotSpansArrowRequest) Reset() {
	*x = GetHotSpansArrowRequest{}
	mi := &file_ingestion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotSpansArrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotSpansArrowRequest) ProtoMessage() {}

func (x *GetHotSpansArrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotSpansArrowRequest.ProtoReflect.Descriptor instead.
func (*GetHotSpansArrowRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{4}
}

func (x *GetHotSpansArrowRequest) GetSinceWarmUlid() []byte {
	if x != nil {
		return x.SinceWarmUlid
	}
	return nil
}

func (x *GetHotSpansArrowRequest) GetTraceId() string {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return ""
}

func (x *GetHotSpansArrowRequest) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

func (x *GetHotSpansArrowRequest) GetRootOnly() bool {
	if x != nil {
		return x.RootOnly
	}
	return false
}

func (x *GetHotSpansArrowRequest) GetWorkflowOnly() bool {
	if x != nil {
		return x.WorkflowOnly
	}
	return false
}

func (x *GetHotSpansArrowRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetWarmCursorRequest requests the current warm snapshot cursor state.
type GetWarmCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarmCursorRequest) Reset() {
	*x = GetWarmCursorRequest{}
	mi := &file_ingestion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarmCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarmCursorRequest) ProtoMessage() {}

func (x *GetWarmCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarmCursorRequest.ProtoReflect.Descriptor instead.
func (*GetWarmCursorRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{5}
}

// GetWarmCursorResponse contains the warm snapshot cursor state.
type GetWarmCursorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Last span ULID written to warm snapshot (empty if no snapshots)
	LastWarmUlid []byte `protobuf:"bytes,1,opt,name=last_warm_ulid,json=lastWarmUlid,proto3" json:"last_warm_ulid,omitempty"`
	// Timestamp of last warm snapshot in nanoseconds
	LastWarmTimeNs int64 `protobuf:"varint,2,opt,name=last_warm_time_ns,json=lastWarmTimeNs,proto3" json:"last_warm_time_ns,omitempty"`
	// Number of warm parquet files currently in tmp/
	WarmFileCount int32 `protobuf:"varint,3,opt,name=warm_file_count,json=warmFileCount,proto3" json:"warm_file_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarmCursorResponse) Reset() {
	*x = GetWarmCursorResponse{}
	mi := &file_ingestion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarmCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarmCursorResponse) ProtoMessage() {}

func (x *GetWarmCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarmCursorResponse.ProtoReflect.Descriptor instead.
func (*GetWarmCursorResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{6}
}

func (x *GetWarmCursorResponse) GetLastWarmUlid() []byte {
	if x != nil {
		return x.LastWarmUlid
	}
	return nil
}

func (x *GetWarmCursorResponse) GetLastWarmTimeNs() int64 {
	if x != nil {
		return x.LastWarmTimeNs
	}
	return 0
}

func (x *GetWarmCursorResponse) GetWarmFileCount() int32 {
	if x != nil {
		return x.WarmFileCount
	}
	return 0
}

// GetWALDistinctServiceNamesRequest requests all distinct service names in WAL.
// DEPRECATED: Use GetHotSpansArrow + DataFusion instead.
type GetWALDistinctServiceNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALDistinctServiceNamesRequest) Reset() {
	*x = GetWALDistinctServiceNamesRequest{}
	mi := &file_ingestion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALDistinctServiceNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALDistinctServiceNamesRequest) ProtoMessage() {}

func (x *GetWALDistinctServiceNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALDistinctServiceNamesRequest.ProtoReflect.Descriptor instead.
func (*GetWALDistinctServiceNamesRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{7}
}

// GetWALDistinctServiceNamesResponse contains the list of service names.
type GetWALDistinctServiceNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceNames  []string               `protobuf:"bytes,1,rep,name=service_names,json=serviceNames,proto3" json:"service_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALDistinctServiceNamesResponse) Reset() {
	*x = GetWALDistinctServiceNamesResponse{}
	mi := &file_ingestion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALDistinctServiceNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALDistinctServiceNamesResponse) ProtoMessage() {}

func (x *GetWALDistinctServiceNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALDistinctServiceNamesResponse.ProtoReflect.Descriptor instead.
func (*GetWALDistinctServiceNamesResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{8}
}

func (x *GetWALDistinctServiceNamesResponse) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

// FlushWALRequest triggers a manual WAL flush.
type FlushWALRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushWALRequest) Reset() {
	*x = FlushWALRequest{}
	mi := &file_ingestion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushWALRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushWALRequest) ProtoMessage() {}

func (x *FlushWALRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushWALRequest.ProtoReflect.Descriptor instead.
func (*FlushWALRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{9}
}

// FlushWALResponse contains the result of a flush operation.
type FlushWALResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error details if success=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushWALResponse) Reset() {
	*x = FlushWALResponse{}
	mi := &file_ingestion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushWALResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushWALResponse) ProtoMessage() {}

func (x *FlushWALResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushWALResponse.ProtoReflect.Descriptor instead.
func (*FlushWALResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{10}
}

func (x *FlushWALResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FlushWALResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_ingestion_proto protoreflect.FileDescriptor

const file_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x0fingestion.proto\x12\tingestion\"W\n" +
	"\x10ReadSpansRequest\x12$\n" +
	"\x0estart_key_ulid\x18\x01 \x01(\fR\fstartKeyUlid\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\rR\tbatchSize\"\x9d\x01\n" +
	"\x11ReadSpansResponse\x12\x19\n" +
	"\bkey_ulid\x18\x01 \x01(\fR\akeyUlid\x12\x1d\n" +
	"\n" +
	"span_bytes\x18\x02 \x01(\fR\tspanBytes\x12%\n" +
	"\x0eresource_bytes\x18\x03 \x01(\fR\rresourceBytes\x12'\n" +
	"\x0fremaining_count\x18\x04 \x01(\x04R\x0eremainingCount\"\xd7\x01\n" +
	"\x17GetWALSpansArrowRequest\x12\x1e\n" +
	"\btrace_id\x18\x01 \x01(\tH\x00R\atraceId\x88\x01\x01\x12&\n" +
	"\fservice_name\x18\x02 \x01(\tH\x01R\vserviceName\x88\x01\x01\x12\x1b\n" +
	"\troot_only\x18\x03 \x01(\bR\brootOnly\x12#\n" +
	"\rworkflow_only\x18\x04 \x01(\bR\fworkflowOnly\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limitB\v\n" +
	"\t_trace_idB\x0f\n" +
	"\r_service_name\"_\n" +
	"\n" +
	"ArrowBatch\x12\x1b\n" +
	"\tipc_bytes\x18\x01 \x01(\fR\bipcBytes\x12\x1b\n" +
	"\trow_count\x18\x02 \x01(\x05R\browCount\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"\x98\x02\n" +
	"\x17GetHotSpansArrowRequest\x12+\n" +
	"\x0fsince_warm_ulid\x18\x01 \x01(\fH\x00R\rsinceWarmUlid\x88\x01\x01\x12\x1e\n" +
	"\btrace_id\x18\x02 \x01(\tH\x01R\atraceId\x88\x01\x01\x12&\n" +
	"\fservice_name\x18\x03 \x01(\tH\x02R\vserviceName\x88\x01\x01\x12\x1b\n" +
	"\troot_only\x18\x04 \x01(\bR\brootOnly\x12#\n" +
	"\rworkflow_only\x18\x05 \x01(\bR\fworkflowOnly\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limitB\x12\n" +
	"\x10_since_warm_ulidB\v\n" +
	"\t_trace_idB\x0f\n" +
	"\r_service_name\"\x16\n" +
	"\x14GetWarmCursorRequest\"\x90\x01\n" +
	"\x15GetWarmCursorResponse\x12$\n" +
	"\x0elast_warm_ulid\x18\x01 \x01(\fR\flastWarmUlid\x12)\n" +
	"\x11last_warm_time_ns\x18\x02 \x01(\x03R\x0elastWarmTimeNs\x12&\n" +
	"\x0fwarm_file_count\x18\x03 \x01(\x05R\rwarmFileCount\"#\n" +
	"!GetWALDistinctServiceNamesRequest\"I\n" +
	"\"GetWALDistinctServiceNamesResponse\x12#\n" +
	"\rservice_names\x18\x01 \x03(\tR\fserviceNames\"\x11\n" +
	"\x0fFlushWALRequest\"Q\n" +
	"\x10FlushWALResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xa6\x04\n" +
	"\x18InternalIngestionService\x12J\n" +
	"\tReadSpans\x12\x1b.ingestion.ReadSpansRequest\x1a\x1c.ingestion.ReadSpansResponse\"\x000\x01\x12Q\n" +
	"\x10GetWALSpansArrow\x12\".ingestion.GetWALSpansArrowRequest\x1a\x15.ingestion.ArrowBatch\"\x000\x01\x12Q\n" +
	"\x10GetHotSpansArrow\x12\".ingestion.GetHotSpansArrowRequest\x1a\x15.ingestion.ArrowBatch\"\x000\x01\x12T\n" +
	"\rGetWarmCursor\x12\x1f.ingestion.GetWarmCursorRequest\x1a .ingestion.GetWarmCursorResponse\"\x00\x12{\n" +
	"\x1aGetWALDistinctServiceNames\x12,.ingestion.GetWALDistinctServiceNamesRequest\x1a-.ingestion.GetWALDistinctServiceNamesResponse\"\x00\x12E\n" +
	"\bFlushWAL\x12\x1a.ingestion.FlushWALRequest\x1a\x1b.ingestion.FlushWALResponse\"\x00B\rZ\v.;proto_genb\x06proto3"

var (
	file_ingestion_proto_rawDescOnce sync.Once
	file_ingestion_proto_rawDescData []byte
)

func file_ingestion_proto_rawDescGZIP() []byte {
	file_ingestion_proto_rawDescOnce.Do(func() {
		file_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)))
	})
	return file_ingestion_proto_rawDescData
}

var file_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ingestion_proto_goTypes = []any{
	(*ReadSpansRequest)(nil),                   // 0: ingestion.ReadSpansRequest
	(*ReadSpansResponse)(nil),                  // 1: ingestion.ReadSpansResponse
	(*GetWALSpansArrowRequest)(nil),            // 2: ingestion.GetWALSpansArrowRequest
	(*ArrowBatch)(nil),                         // 3: ingestion.ArrowBatch
	(*GetHotSpansArrowRequest)(nil),            // 4: ingestion.GetHotSpansArrowRequest
	(*GetWarmCursorRequest)(nil),               // 5: ingestion.GetWarmCursorRequest
	(*GetWarmCursorResponse)(nil),              // 6: ingestion.GetWarmCursorResponse
	(*GetWALDistinctServiceNamesRequest)(nil),  // 7: ingestion.GetWALDistinctServiceNamesRequest
	(*GetWALDistinctServiceNamesResponse)(nil), // 8: ingestion.GetWALDistinctServiceNamesResponse
	(*FlushWALRequest)(nil),                    // 9: ingestion.FlushWALRequest
	(*FlushWALResponse)(nil),                   // 10: ingestion.FlushWALResponse
}
var file_ingestion_proto_depIdxs = []int32{
	0,  // 0: ingestion.InternalIngestionService.ReadSpans:input_type -> ingestion.ReadSpansRequest
	2,  // 1: ingestion.InternalIngestionService.GetWALSpansArrow:input_type -> ingestion.GetWALSpansArrowRequest
	4,  // 2: ingestion.InternalIngestionService.GetHotSpansArrow:input_type -> ingestion.GetHotSpansArrowRequest
	5,  // 3: ingestion.InternalIngestionService.GetWarmCursor:input_type -> ingestion.GetWarmCursorRequest
	7,  // 4: ingestion.InternalIngestionService.GetWALDistinctServiceNames:input_type -> ingestion.GetWALDistinctServiceNamesRequest
	9,  // 5: ingestion.InternalIngestionService.FlushWAL:input_type -> ingestion.FlushWALRequest
	1,  // 6: ingestion.InternalIngestionService.ReadSpans:output_type -> ingestion.ReadSpansResponse
	3,  // 7: ingestion.InternalIngestionService.GetWALSpansArrow:output_type -> ingestion.ArrowBatch
	3,  // 8: ingestion.InternalIngestionService.GetHotSpansArrow:output_type -> ingestion.ArrowBatch
	6,  // 9: ingestion.InternalIngestionService.GetWarmCursor:output_type -> ingestion.GetWarmCursorResponse
	8,  // 10: ingestion.InternalIngestionService.GetWALDistinctServiceNames:output_type -> ingestion.GetWALDistinctServiceNamesResponse
	10, // 11: ingestion.InternalIngestionService.FlushWAL:output_type -> ingestion.FlushWALResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ingestion_proto_init() }
func file_ingestion_proto_init() {
	if File_ingestion_proto != nil {
		return
	}
	file_ingestion_proto_msgTypes[2].OneofWrappers = []any{}
	file_ingestion_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_proto_goTypes,
		DependencyIndexes: file_ingestion_proto_depIdxs,
		MessageInfos:      file_ingestion_proto_msgTypes,
	}.Build()
	File_ingestion_proto = out.File
	file_ingestion_proto_goTypes = nil
	file_ingestion_proto_depIdxs = nil
}
