// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: ingestion.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadSpansRequest defines the parameters for requesting a batch of spans.
type ReadSpansRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ULID of the last span successfully processed by the client.
	// The server will return spans that were received *after* this key.
	// If empty, the stream will start from the oldest available span.
	StartKeyUlid []byte `protobuf:"bytes,1,opt,name=start_key_ulid,json=startKeyUlid,proto3" json:"start_key_ulid,omitempty"`
	// The maximum number of spans to return in the batch.
	BatchSize     uint32 `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSpansRequest) Reset() {
	*x = ReadSpansRequest{}
	mi := &file_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSpansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSpansRequest) ProtoMessage() {}

func (x *ReadSpansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSpansRequest.ProtoReflect.Descriptor instead.
func (*ReadSpansRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *ReadSpansRequest) GetStartKeyUlid() []byte {
	if x != nil {
		return x.StartKeyUlid
	}
	return nil
}

func (x *ReadSpansRequest) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

// ReadSpansResponse contains a single span from the WAL.
type ReadSpansResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ULID key of the span, which also serves as its timestamp.
	KeyUlid []byte `protobuf:"bytes,1,opt,name=key_ulid,json=keyUlid,proto3" json:"key_ulid,omitempty"`
	// The raw, serialized protobuf bytes of the OTel span.
	SpanBytes []byte `protobuf:"bytes,2,opt,name=span_bytes,json=spanBytes,proto3" json:"span_bytes,omitempty"`
	// The raw, serialized protobuf bytes of the OTel resource.
	ResourceBytes []byte `protobuf:"bytes,3,opt,name=resource_bytes,json=resourceBytes,proto3" json:"resource_bytes,omitempty"`
	// The number of spans remaining in the WAL after this batch was retrieved.
	// This count is decremented atomically when the batch is read.
	RemainingCount uint64 `protobuf:"varint,4,opt,name=remaining_count,json=remainingCount,proto3" json:"remaining_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadSpansResponse) Reset() {
	*x = ReadSpansResponse{}
	mi := &file_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSpansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSpansResponse) ProtoMessage() {}

func (x *ReadSpansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSpansResponse.ProtoReflect.Descriptor instead.
func (*ReadSpansResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *ReadSpansResponse) GetKeyUlid() []byte {
	if x != nil {
		return x.KeyUlid
	}
	return nil
}

func (x *ReadSpansResponse) GetSpanBytes() []byte {
	if x != nil {
		return x.SpanBytes
	}
	return nil
}

func (x *ReadSpansResponse) GetResourceBytes() []byte {
	if x != nil {
		return x.ResourceBytes
	}
	return nil
}

func (x *ReadSpansResponse) GetRemainingCount() uint64 {
	if x != nil {
		return x.RemainingCount
	}
	return 0
}

// SpanData contains a fully decoded span with all fields extracted.
// Used for query responses where the caller needs structured data.
type SpanData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SpanId                 string                 `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	TraceId                string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ParentSpanId           string                 `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	ServiceName            string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Name                   string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SpanKind               int32                  `protobuf:"varint,6,opt,name=span_kind,json=spanKind,proto3" json:"span_kind,omitempty"`
	StartTimeUnixNano      int64                  `protobuf:"varint,7,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	EndTimeUnixNano        int64                  `protobuf:"varint,8,opt,name=end_time_unix_nano,json=endTimeUnixNano,proto3" json:"end_time_unix_nano,omitempty"`
	DurationNs             int64                  `protobuf:"varint,9,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	StatusCode             int32                  `protobuf:"varint,10,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMessage          string                 `protobuf:"bytes,11,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	AttributesJson         string                 `protobuf:"bytes,12,opt,name=attributes_json,json=attributesJson,proto3" json:"attributes_json,omitempty"`                           // JSON-encoded attributes
	EventsJson             string                 `protobuf:"bytes,13,opt,name=events_json,json=eventsJson,proto3" json:"events_json,omitempty"`                                       // JSON-encoded events
	ResourceAttributesJson string                 `protobuf:"bytes,14,opt,name=resource_attributes_json,json=resourceAttributesJson,proto3" json:"resource_attributes_json,omitempty"` // JSON-encoded resource attributes
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SpanData) Reset() {
	*x = SpanData{}
	mi := &file_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanData) ProtoMessage() {}

func (x *SpanData) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanData.ProtoReflect.Descriptor instead.
func (*SpanData) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *SpanData) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *SpanData) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SpanData) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *SpanData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SpanData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpanData) GetSpanKind() int32 {
	if x != nil {
		return x.SpanKind
	}
	return 0
}

func (x *SpanData) GetStartTimeUnixNano() int64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *SpanData) GetEndTimeUnixNano() int64 {
	if x != nil {
		return x.EndTimeUnixNano
	}
	return 0
}

func (x *SpanData) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *SpanData) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SpanData) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *SpanData) GetAttributesJson() string {
	if x != nil {
		return x.AttributesJson
	}
	return ""
}

func (x *SpanData) GetEventsJson() string {
	if x != nil {
		return x.EventsJson
	}
	return ""
}

func (x *SpanData) GetResourceAttributesJson() string {
	if x != nil {
		return x.ResourceAttributesJson
	}
	return ""
}

// GetWALSpansByTraceIdRequest requests all spans matching a trace ID.
type GetWALSpansByTraceIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALSpansByTraceIdRequest) Reset() {
	*x = GetWALSpansByTraceIdRequest{}
	mi := &file_ingestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALSpansByTraceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALSpansByTraceIdRequest) ProtoMessage() {}

func (x *GetWALSpansByTraceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALSpansByTraceIdRequest.ProtoReflect.Descriptor instead.
func (*GetWALSpansByTraceIdRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{3}
}

func (x *GetWALSpansByTraceIdRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// GetWALDistinctServiceNamesRequest requests all distinct service names in WAL.
type GetWALDistinctServiceNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALDistinctServiceNamesRequest) Reset() {
	*x = GetWALDistinctServiceNamesRequest{}
	mi := &file_ingestion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALDistinctServiceNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALDistinctServiceNamesRequest) ProtoMessage() {}

func (x *GetWALDistinctServiceNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALDistinctServiceNamesRequest.ProtoReflect.Descriptor instead.
func (*GetWALDistinctServiceNamesRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{4}
}

// GetWALDistinctServiceNamesResponse contains the list of service names.
type GetWALDistinctServiceNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceNames  []string               `protobuf:"bytes,1,rep,name=service_names,json=serviceNames,proto3" json:"service_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALDistinctServiceNamesResponse) Reset() {
	*x = GetWALDistinctServiceNamesResponse{}
	mi := &file_ingestion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALDistinctServiceNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALDistinctServiceNamesResponse) ProtoMessage() {}

func (x *GetWALDistinctServiceNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALDistinctServiceNamesResponse.ProtoReflect.Descriptor instead.
func (*GetWALDistinctServiceNamesResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{5}
}

func (x *GetWALDistinctServiceNamesResponse) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

// GetWALRootSpansRequest requests root spans for a service.
type GetWALRootSpansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Maximum number of root spans to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALRootSpansRequest) Reset() {
	*x = GetWALRootSpansRequest{}
	mi := &file_ingestion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALRootSpansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALRootSpansRequest) ProtoMessage() {}

func (x *GetWALRootSpansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALRootSpansRequest.ProtoReflect.Descriptor instead.
func (*GetWALRootSpansRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{6}
}

func (x *GetWALRootSpansRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetWALRootSpansRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetWALSpansByServiceRequest requests all spans for a service.
type GetWALSpansByServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Maximum number of spans to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALSpansByServiceRequest) Reset() {
	*x = GetWALSpansByServiceRequest{}
	mi := &file_ingestion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALSpansByServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALSpansByServiceRequest) ProtoMessage() {}

func (x *GetWALSpansByServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALSpansByServiceRequest.ProtoReflect.Descriptor instead.
func (*GetWALSpansByServiceRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{7}
}

func (x *GetWALSpansByServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetWALSpansByServiceRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetWALWorkflowSpansRequest requests workflow-type spans for a service.
type GetWALWorkflowSpansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Maximum number of workflow spans to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALWorkflowSpansRequest) Reset() {
	*x = GetWALWorkflowSpansRequest{}
	mi := &file_ingestion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALWorkflowSpansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALWorkflowSpansRequest) ProtoMessage() {}

func (x *GetWALWorkflowSpansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALWorkflowSpansRequest.ProtoReflect.Descriptor instead.
func (*GetWALWorkflowSpansRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{8}
}

func (x *GetWALWorkflowSpansRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetWALWorkflowSpansRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// FlushWALRequest triggers a manual WAL flush.
type FlushWALRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushWALRequest) Reset() {
	*x = FlushWALRequest{}
	mi := &file_ingestion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushWALRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushWALRequest) ProtoMessage() {}

func (x *FlushWALRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushWALRequest.ProtoReflect.Descriptor instead.
func (*FlushWALRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{9}
}

// FlushWALResponse contains the result of a flush operation.
type FlushWALResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error details if success=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushWALResponse) Reset() {
	*x = FlushWALResponse{}
	mi := &file_ingestion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushWALResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushWALResponse) ProtoMessage() {}

func (x *FlushWALResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushWALResponse.ProtoReflect.Descriptor instead.
func (*FlushWALResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{10}
}

func (x *FlushWALResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FlushWALResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_ingestion_proto protoreflect.FileDescriptor

const file_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x0fingestion.proto\x12\tingestion\"W\n" +
	"\x10ReadSpansRequest\x12$\n" +
	"\x0estart_key_ulid\x18\x01 \x01(\fR\fstartKeyUlid\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\rR\tbatchSize\"\x9d\x01\n" +
	"\x11ReadSpansResponse\x12\x19\n" +
	"\bkey_ulid\x18\x01 \x01(\fR\akeyUlid\x12\x1d\n" +
	"\n" +
	"span_bytes\x18\x02 \x01(\fR\tspanBytes\x12%\n" +
	"\x0eresource_bytes\x18\x03 \x01(\fR\rresourceBytes\x12'\n" +
	"\x0fremaining_count\x18\x04 \x01(\x04R\x0eremainingCount\"\x83\x04\n" +
	"\bSpanData\x12\x17\n" +
	"\aspan_id\x18\x01 \x01(\tR\x06spanId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1b\n" +
	"\tspan_kind\x18\x06 \x01(\x05R\bspanKind\x12/\n" +
	"\x14start_time_unix_nano\x18\a \x01(\x03R\x11startTimeUnixNano\x12+\n" +
	"\x12end_time_unix_nano\x18\b \x01(\x03R\x0fendTimeUnixNano\x12\x1f\n" +
	"\vduration_ns\x18\t \x01(\x03R\n" +
	"durationNs\x12\x1f\n" +
	"\vstatus_code\x18\n" +
	" \x01(\x05R\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\v \x01(\tR\rstatusMessage\x12'\n" +
	"\x0fattributes_json\x18\f \x01(\tR\x0eattributesJson\x12\x1f\n" +
	"\vevents_json\x18\r \x01(\tR\n" +
	"eventsJson\x128\n" +
	"\x18resource_attributes_json\x18\x0e \x01(\tR\x16resourceAttributesJson\"8\n" +
	"\x1bGetWALSpansByTraceIdRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"#\n" +
	"!GetWALDistinctServiceNamesRequest\"I\n" +
	"\"GetWALDistinctServiceNamesResponse\x12#\n" +
	"\rservice_names\x18\x01 \x03(\tR\fserviceNames\"Q\n" +
	"\x16GetWALRootSpansRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"V\n" +
	"\x1bGetWALSpansByServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"U\n" +
	"\x1aGetWALWorkflowSpansRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x11\n" +
	"\x0fFlushWALRequest\"Q\n" +
	"\x10FlushWALResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\x82\x05\n" +
	"\x18InternalIngestionService\x12J\n" +
	"\tReadSpans\x12\x1b.ingestion.ReadSpansRequest\x1a\x1c.ingestion.ReadSpansResponse\"\x000\x01\x12W\n" +
	"\x14GetWALSpansByTraceId\x12&.ingestion.GetWALSpansByTraceIdRequest\x1a\x13.ingestion.SpanData\"\x000\x01\x12{\n" +
	"\x1aGetWALDistinctServiceNames\x12,.ingestion.GetWALDistinctServiceNamesRequest\x1a-.ingestion.GetWALDistinctServiceNamesResponse\"\x00\x12M\n" +
	"\x0fGetWALRootSpans\x12!.ingestion.GetWALRootSpansRequest\x1a\x13.ingestion.SpanData\"\x000\x01\x12W\n" +
	"\x14GetWALSpansByService\x12&.ingestion.GetWALSpansByServiceRequest\x1a\x13.ingestion.SpanData\"\x000\x01\x12U\n" +
	"\x13GetWALWorkflowSpans\x12%.ingestion.GetWALWorkflowSpansRequest\x1a\x13.ingestion.SpanData\"\x000\x01\x12E\n" +
	"\bFlushWAL\x12\x1a.ingestion.FlushWALRequest\x1a\x1b.ingestion.FlushWALResponse\"\x00B\rZ\v.;proto_genb\x06proto3"

var (
	file_ingestion_proto_rawDescOnce sync.Once
	file_ingestion_proto_rawDescData []byte
)

func file_ingestion_proto_rawDescGZIP() []byte {
	file_ingestion_proto_rawDescOnce.Do(func() {
		file_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)))
	})
	return file_ingestion_proto_rawDescData
}

var file_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ingestion_proto_goTypes = []any{
	(*ReadSpansRequest)(nil),                   // 0: ingestion.ReadSpansRequest
	(*ReadSpansResponse)(nil),                  // 1: ingestion.ReadSpansResponse
	(*SpanData)(nil),                           // 2: ingestion.SpanData
	(*GetWALSpansByTraceIdRequest)(nil),        // 3: ingestion.GetWALSpansByTraceIdRequest
	(*GetWALDistinctServiceNamesRequest)(nil),  // 4: ingestion.GetWALDistinctServiceNamesRequest
	(*GetWALDistinctServiceNamesResponse)(nil), // 5: ingestion.GetWALDistinctServiceNamesResponse
	(*GetWALRootSpansRequest)(nil),             // 6: ingestion.GetWALRootSpansRequest
	(*GetWALSpansByServiceRequest)(nil),        // 7: ingestion.GetWALSpansByServiceRequest
	(*GetWALWorkflowSpansRequest)(nil),         // 8: ingestion.GetWALWorkflowSpansRequest
	(*FlushWALRequest)(nil),                    // 9: ingestion.FlushWALRequest
	(*FlushWALResponse)(nil),                   // 10: ingestion.FlushWALResponse
}
var file_ingestion_proto_depIdxs = []int32{
	0,  // 0: ingestion.InternalIngestionService.ReadSpans:input_type -> ingestion.ReadSpansRequest
	3,  // 1: ingestion.InternalIngestionService.GetWALSpansByTraceId:input_type -> ingestion.GetWALSpansByTraceIdRequest
	4,  // 2: ingestion.InternalIngestionService.GetWALDistinctServiceNames:input_type -> ingestion.GetWALDistinctServiceNamesRequest
	6,  // 3: ingestion.InternalIngestionService.GetWALRootSpans:input_type -> ingestion.GetWALRootSpansRequest
	7,  // 4: ingestion.InternalIngestionService.GetWALSpansByService:input_type -> ingestion.GetWALSpansByServiceRequest
	8,  // 5: ingestion.InternalIngestionService.GetWALWorkflowSpans:input_type -> ingestion.GetWALWorkflowSpansRequest
	9,  // 6: ingestion.InternalIngestionService.FlushWAL:input_type -> ingestion.FlushWALRequest
	1,  // 7: ingestion.InternalIngestionService.ReadSpans:output_type -> ingestion.ReadSpansResponse
	2,  // 8: ingestion.InternalIngestionService.GetWALSpansByTraceId:output_type -> ingestion.SpanData
	5,  // 9: ingestion.InternalIngestionService.GetWALDistinctServiceNames:output_type -> ingestion.GetWALDistinctServiceNamesResponse
	2,  // 10: ingestion.InternalIngestionService.GetWALRootSpans:output_type -> ingestion.SpanData
	2,  // 11: ingestion.InternalIngestionService.GetWALSpansByService:output_type -> ingestion.SpanData
	2,  // 12: ingestion.InternalIngestionService.GetWALWorkflowSpans:output_type -> ingestion.SpanData
	10, // 13: ingestion.InternalIngestionService.FlushWAL:output_type -> ingestion.FlushWALResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ingestion_proto_init() }
func file_ingestion_proto_init() {
	if File_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_proto_goTypes,
		DependencyIndexes: file_ingestion_proto_depIdxs,
		MessageInfos:      file_ingestion_proto_msgTypes,
	}.Build()
	File_ingestion_proto = out.File
	file_ingestion_proto_goTypes = nil
	file_ingestion_proto_depIdxs = nil
}
