// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: ingestion.proto

package proto_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalIngestionService_ReadSpans_FullMethodName                  = "/ingestion.InternalIngestionService/ReadSpans"
	InternalIngestionService_GetWALSpansArrow_FullMethodName           = "/ingestion.InternalIngestionService/GetWALSpansArrow"
	InternalIngestionService_GetHotSpansArrow_FullMethodName           = "/ingestion.InternalIngestionService/GetHotSpansArrow"
	InternalIngestionService_GetWarmCursor_FullMethodName              = "/ingestion.InternalIngestionService/GetWarmCursor"
	InternalIngestionService_GetWALDistinctServiceNames_FullMethodName = "/ingestion.InternalIngestionService/GetWALDistinctServiceNames"
	InternalIngestionService_FlushWAL_FullMethodName                   = "/ingestion.InternalIngestionService/FlushWAL"
)

// InternalIngestionServiceClient is the client API for InternalIngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalIngestionService provides an API for the main backend to read
// spans from the SQLite WAL.
type InternalIngestionServiceClient interface {
	// ReadSpans reads a batch of spans from the WAL, starting after the
	// specified ULID. This is a server-streaming RPC.
	ReadSpans(ctx context.Context, in *ReadSpansRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadSpansResponse], error)
	// GetWALSpansArrow returns spans from WAL as Arrow IPC bytes.
	// Supports filtering by trace_id, service_name, root_only, and workflow_only.
	// Used for unified DataFusion queries combining WAL and Parquet data.
	GetWALSpansArrow(ctx context.Context, in *GetWALSpansArrowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArrowBatch], error)
	// GetHotSpansArrow returns only HOT tier spans (since last warm snapshot).
	// This is the three-tier architecture query that returns only the newest data.
	GetHotSpansArrow(ctx context.Context, in *GetHotSpansArrowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArrowBatch], error)
	// GetWarmCursor returns the current warm snapshot cursor state.
	// Used by Python to know what's in warm tier vs hot tier.
	GetWarmCursor(ctx context.Context, in *GetWarmCursorRequest, opts ...grpc.CallOption) (*GetWarmCursorResponse, error)
	// GetWALDistinctServiceNames returns all distinct service names currently in the WAL.
	// Used to merge with Parquet-indexed services for complete listing.
	// DEPRECATED: Use GetHotSpansArrow + DataFusion instead.
	GetWALDistinctServiceNames(ctx context.Context, in *GetWALDistinctServiceNamesRequest, opts ...grpc.CallOption) (*GetWALDistinctServiceNamesResponse, error)
	// FlushWAL triggers an immediate flush of WAL data to Parquet files.
	FlushWAL(ctx context.Context, in *FlushWALRequest, opts ...grpc.CallOption) (*FlushWALResponse, error)
}

type internalIngestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalIngestionServiceClient(cc grpc.ClientConnInterface) InternalIngestionServiceClient {
	return &internalIngestionServiceClient{cc}
}

func (c *internalIngestionServiceClient) ReadSpans(ctx context.Context, in *ReadSpansRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadSpansResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InternalIngestionService_ServiceDesc.Streams[0], InternalIngestionService_ReadSpans_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadSpansRequest, ReadSpansResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalIngestionService_ReadSpansClient = grpc.ServerStreamingClient[ReadSpansResponse]

func (c *internalIngestionServiceClient) GetWALSpansArrow(ctx context.Context, in *GetWALSpansArrowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArrowBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InternalIngestionService_ServiceDesc.Streams[1], InternalIngestionService_GetWALSpansArrow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetWALSpansArrowRequest, ArrowBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalIngestionService_GetWALSpansArrowClient = grpc.ServerStreamingClient[ArrowBatch]

func (c *internalIngestionServiceClient) GetHotSpansArrow(ctx context.Context, in *GetHotSpansArrowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArrowBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InternalIngestionService_ServiceDesc.Streams[2], InternalIngestionService_GetHotSpansArrow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetHotSpansArrowRequest, ArrowBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalIngestionService_GetHotSpansArrowClient = grpc.ServerStreamingClient[ArrowBatch]

func (c *internalIngestionServiceClient) GetWarmCursor(ctx context.Context, in *GetWarmCursorRequest, opts ...grpc.CallOption) (*GetWarmCursorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWarmCursorResponse)
	err := c.cc.Invoke(ctx, InternalIngestionService_GetWarmCursor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalIngestionServiceClient) GetWALDistinctServiceNames(ctx context.Context, in *GetWALDistinctServiceNamesRequest, opts ...grpc.CallOption) (*GetWALDistinctServiceNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWALDistinctServiceNamesResponse)
	err := c.cc.Invoke(ctx, InternalIngestionService_GetWALDistinctServiceNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalIngestionServiceClient) FlushWAL(ctx context.Context, in *FlushWALRequest, opts ...grpc.CallOption) (*FlushWALResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushWALResponse)
	err := c.cc.Invoke(ctx, InternalIngestionService_FlushWAL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalIngestionServiceServer is the server API for InternalIngestionService service.
// All implementations must embed UnimplementedInternalIngestionServiceServer
// for forward compatibility.
//
// InternalIngestionService provides an API for the main backend to read
// spans from the SQLite WAL.
type InternalIngestionServiceServer interface {
	// ReadSpans reads a batch of spans from the WAL, starting after the
	// specified ULID. This is a server-streaming RPC.
	ReadSpans(*ReadSpansRequest, grpc.ServerStreamingServer[ReadSpansResponse]) error
	// GetWALSpansArrow returns spans from WAL as Arrow IPC bytes.
	// Supports filtering by trace_id, service_name, root_only, and workflow_only.
	// Used for unified DataFusion queries combining WAL and Parquet data.
	GetWALSpansArrow(*GetWALSpansArrowRequest, grpc.ServerStreamingServer[ArrowBatch]) error
	// GetHotSpansArrow returns only HOT tier spans (since last warm snapshot).
	// This is the three-tier architecture query that returns only the newest data.
	GetHotSpansArrow(*GetHotSpansArrowRequest, grpc.ServerStreamingServer[ArrowBatch]) error
	// GetWarmCursor returns the current warm snapshot cursor state.
	// Used by Python to know what's in warm tier vs hot tier.
	GetWarmCursor(context.Context, *GetWarmCursorRequest) (*GetWarmCursorResponse, error)
	// GetWALDistinctServiceNames returns all distinct service names currently in the WAL.
	// Used to merge with Parquet-indexed services for complete listing.
	// DEPRECATED: Use GetHotSpansArrow + DataFusion instead.
	GetWALDistinctServiceNames(context.Context, *GetWALDistinctServiceNamesRequest) (*GetWALDistinctServiceNamesResponse, error)
	// FlushWAL triggers an immediate flush of WAL data to Parquet files.
	FlushWAL(context.Context, *FlushWALRequest) (*FlushWALResponse, error)
	mustEmbedUnimplementedInternalIngestionServiceServer()
}

// UnimplementedInternalIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalIngestionServiceServer struct{}

func (UnimplementedInternalIngestionServiceServer) ReadSpans(*ReadSpansRequest, grpc.ServerStreamingServer[ReadSpansResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReadSpans not implemented")
}
func (UnimplementedInternalIngestionServiceServer) GetWALSpansArrow(*GetWALSpansArrowRequest, grpc.ServerStreamingServer[ArrowBatch]) error {
	return status.Errorf(codes.Unimplemented, "method GetWALSpansArrow not implemented")
}
func (UnimplementedInternalIngestionServiceServer) GetHotSpansArrow(*GetHotSpansArrowRequest, grpc.ServerStreamingServer[ArrowBatch]) error {
	return status.Errorf(codes.Unimplemented, "method GetHotSpansArrow not implemented")
}
func (UnimplementedInternalIngestionServiceServer) GetWarmCursor(context.Context, *GetWarmCursorRequest) (*GetWarmCursorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWarmCursor not implemented")
}
func (UnimplementedInternalIngestionServiceServer) GetWALDistinctServiceNames(context.Context, *GetWALDistinctServiceNamesRequest) (*GetWALDistinctServiceNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWALDistinctServiceNames not implemented")
}
func (UnimplementedInternalIngestionServiceServer) FlushWAL(context.Context, *FlushWALRequest) (*FlushWALResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlushWAL not implemented")
}
func (UnimplementedInternalIngestionServiceServer) mustEmbedUnimplementedInternalIngestionServiceServer() {
}
func (UnimplementedInternalIngestionServiceServer) testEmbeddedByValue() {}

// UnsafeInternalIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalIngestionServiceServer will
// result in compilation errors.
type UnsafeInternalIngestionServiceServer interface {
	mustEmbedUnimplementedInternalIngestionServiceServer()
}

func RegisterInternalIngestionServiceServer(s grpc.ServiceRegistrar, srv InternalIngestionServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalIngestionService_ServiceDesc, srv)
}

func _InternalIngestionService_ReadSpans_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadSpansRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InternalIngestionServiceServer).ReadSpans(m, &grpc.GenericServerStream[ReadSpansRequest, ReadSpansResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalIngestionService_ReadSpansServer = grpc.ServerStreamingServer[ReadSpansResponse]

func _InternalIngestionService_GetWALSpansArrow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWALSpansArrowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InternalIngestionServiceServer).GetWALSpansArrow(m, &grpc.GenericServerStream[GetWALSpansArrowRequest, ArrowBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalIngestionService_GetWALSpansArrowServer = grpc.ServerStreamingServer[ArrowBatch]

func _InternalIngestionService_GetHotSpansArrow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetHotSpansArrowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InternalIngestionServiceServer).GetHotSpansArrow(m, &grpc.GenericServerStream[GetHotSpansArrowRequest, ArrowBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalIngestionService_GetHotSpansArrowServer = grpc.ServerStreamingServer[ArrowBatch]

func _InternalIngestionService_GetWarmCursor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWarmCursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalIngestionServiceServer).GetWarmCursor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalIngestionService_GetWarmCursor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalIngestionServiceServer).GetWarmCursor(ctx, req.(*GetWarmCursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalIngestionService_GetWALDistinctServiceNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWALDistinctServiceNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalIngestionServiceServer).GetWALDistinctServiceNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalIngestionService_GetWALDistinctServiceNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalIngestionServiceServer).GetWALDistinctServiceNames(ctx, req.(*GetWALDistinctServiceNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalIngestionService_FlushWAL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushWALRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalIngestionServiceServer).FlushWAL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalIngestionService_FlushWAL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalIngestionServiceServer).FlushWAL(ctx, req.(*FlushWALRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalIngestionService_ServiceDesc is the grpc.ServiceDesc for InternalIngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalIngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingestion.InternalIngestionService",
	HandlerType: (*InternalIngestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWarmCursor",
			Handler:    _InternalIngestionService_GetWarmCursor_Handler,
		},
		{
			MethodName: "GetWALDistinctServiceNames",
			Handler:    _InternalIngestionService_GetWALDistinctServiceNames_Handler,
		},
		{
			MethodName: "FlushWAL",
			Handler:    _InternalIngestionService_FlushWAL_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadSpans",
			Handler:       _InternalIngestionService_ReadSpans_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetWALSpansArrow",
			Handler:       _InternalIngestionService_GetWALSpansArrow_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetHotSpansArrow",
			Handler:       _InternalIngestionService_GetHotSpansArrow_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ingestion.proto",
}
