// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: span_data_container.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SpanDataContainer is a wrapper for storing a span and its resource together.
// This is used internally by the ingestion service to persist spans and their
// associated resources together in SQLite.
//
// Note: This is an internal-only proto, not part of the gRPC service API.
type SpanDataContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpanBytes     []byte                 `protobuf:"bytes,1,opt,name=span_bytes,json=spanBytes,proto3" json:"span_bytes,omitempty"`
	ResourceBytes []byte                 `protobuf:"bytes,2,opt,name=resource_bytes,json=resourceBytes,proto3" json:"resource_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanDataContainer) Reset() {
	*x = SpanDataContainer{}
	mi := &file_span_data_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanDataContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanDataContainer) ProtoMessage() {}

func (x *SpanDataContainer) ProtoReflect() protoreflect.Message {
	mi := &file_span_data_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanDataContainer.ProtoReflect.Descriptor instead.
func (*SpanDataContainer) Descriptor() ([]byte, []int) {
	return file_span_data_container_proto_rawDescGZIP(), []int{0}
}

func (x *SpanDataContainer) GetSpanBytes() []byte {
	if x != nil {
		return x.SpanBytes
	}
	return nil
}

func (x *SpanDataContainer) GetResourceBytes() []byte {
	if x != nil {
		return x.ResourceBytes
	}
	return nil
}

var File_span_data_container_proto protoreflect.FileDescriptor

const file_span_data_container_proto_rawDesc = "" +
	"\n" +
	"\x19span_data_container.proto\x12\x13span_data_container\"Y\n" +
	"\x11SpanDataContainer\x12\x1d\n" +
	"\n" +
	"span_bytes\x18\x01 \x01(\fR\tspanBytes\x12%\n" +
	"\x0eresource_bytes\x18\x02 \x01(\fR\rresourceBytesB\rZ\v.;proto_genb\x06proto3"

var (
	file_span_data_container_proto_rawDescOnce sync.Once
	file_span_data_container_proto_rawDescData []byte
)

func file_span_data_container_proto_rawDescGZIP() []byte {
	file_span_data_container_proto_rawDescOnce.Do(func() {
		file_span_data_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_span_data_container_proto_rawDesc), len(file_span_data_container_proto_rawDesc)))
	})
	return file_span_data_container_proto_rawDescData
}

var file_span_data_container_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_span_data_container_proto_goTypes = []any{
	(*SpanDataContainer)(nil), // 0: span_data_container.SpanDataContainer
}
var file_span_data_container_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_span_data_container_proto_init() }
func file_span_data_container_proto_init() {
	if File_span_data_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_span_data_container_proto_rawDesc), len(file_span_data_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_span_data_container_proto_goTypes,
		DependencyIndexes: file_span_data_container_proto_depIdxs,
		MessageInfos:      file_span_data_container_proto_msgTypes,
	}.Build()
	File_span_data_container_proto = out.File
	file_span_data_container_proto_goTypes = nil
	file_span_data_container_proto_depIdxs = nil
}
